#####################################
##    READ BEFORE CHANGING THIS    ##
#####################################

# We're in the process of evaluating GitHub Actions as a possible replacement
# for Azure Pipelines, and at the moment the configuration is duplicated
# between the two CI providers. Be sure to also change the configuration in
# src/ci/github-actions when changing this file.

#####################################

#
# Azure Pipelines "auto" branch build for Rust on Linux, macOS, and Windows.
#

# pr: none
# trigger:
#   - auto

# variables:
# - group: prod-credentials

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: steps/run.yml
  strategy:
    matrix:
      x86_64-mingw-2:
        SCRIPT: make ci-mingw-subset-2
        INITIAL_RUST_CONFIGURE_ARGS: --build=x86_64-pc-windows-gnu
        CUSTOM_MINGW: 1
